#http://www.123ajedrez.com/reglas-basicas/notacin
from clases.tablero import Tablero

# Inicializar tablero, colocar piezas y mostrar.
tablero = Tablero()
tablero.inicializarPiezas()
tablero.colocarPiezas()
print(tablero)

#tablero.mover("d4", "b")
#tablero.mover("d5", "n")
#tablero.mover("Ag5", "b")
#tablero.mover("Ag4", "n")
#tablero.mover("Ah4", "b")
#tablero.mover("g6", "n")
#tablero.mover("Ag5", "b")
#tablero.mover("Ah5", "n")
#tablero.mover("Af4", "b")
#tablero.mover("a6", "n")
#tablero.mover("e3", "b")
#tablero.mover("a5", "n")
#tablero.mover("Ag5", "b")
#tablero.mover("a4", "n")
#tablero.mover("Af4", "b")
#tablero.mover("a3", "n")
#tablero.mover("g3", "b")
#tablero.mover("xb2", "n")
#tablero.mover("h3", "b")
#tablero.mover("xa1", "n")
#tablero.mover("g4", "b")
#tablero.mover("Axg4", "n")
#tablero.mover("Ac4", "b")
#tablero.mover("Axd1", "n")
#tablero.mover("Cf3", "b")
#tablero.mover("Ah6", "n")
#tablero.mover("Ah2", "b")
#tablero.mover("Axe3", "n")
#tablero.mover("Ag1", "b")

#print("\n" + str(tablero))

tablero.mover('Cf3', 'b')
tablero.mover('h6', 'n')
tablero.mover('e4', 'b')
tablero.mover('f5', 'n')
tablero.mover('h3', 'b')
tablero.mover('a5', 'n')
tablero.mover('b4', 'b')
tablero.mover('g6', 'n')
tablero.mover('Th2', 'b')
tablero.mover('c6', 'n')
tablero.mover('e5', 'b')
tablero.mover('d6', 'n')
tablero.mover('g4', 'b')
tablero.mover('a4', 'n')
tablero.mover('h4', 'b')
tablero.mover('Ta7', 'n')
tablero.mover('c3', 'b')
tablero.mover('Ae6', 'n')
tablero.mover('b5', 'b')
tablero.mover('Ac2', 'n')
tablero.mover('Th1', 'b')
tablero.mover('c5', 'n')
tablero.mover('xf5', 'b')
tablero.mover('Ta5', 'n')
tablero.mover('Ca3', 'b')
tablero.mover('xe5', 'n')
tablero.mover('d4', 'b')
tablero.mover('xd4', 'n')
tablero.mover('Th2', 'b')
tablero.mover('xc3', 'n')
tablero.mover('f6', 'b')
tablero.mover('Axd1', 'n')
tablero.mover('Ce5', 'b')
tablero.mover('xf6', 'n')
tablero.mover('Axb7', 'b')
tablero.mover('Ta8', 'n')
tablero.mover('Ac6', 'b')
tablero.mover('Af4', 'n')
tablero.mover('Th3', 'b')
tablero.mover('Ae3', 'n')
tablero.mover('Axe8', 'b')
tablero.mover('h5', 'n')
tablero.mover('Cd7', 'b')
tablero.mover('Ta5', 'n')
tablero.mover('Ad3', 'b')
tablero.mover('Ad2', 'n')
tablero.mover('Af7', 'b')
tablero.mover('Th6', 'n')
tablero.mover('Th1', 'b')
tablero.mover('Th7', 'n')
tablero.mover('Af5', 'b')
tablero.mover('g5', 'n')
tablero.mover('Ae6', 'b')
tablero.mover('Ae7', 'n')
tablero.mover('Ag1', 'b')
tablero.mover('c2', 'n')
tablero.mover('Tc1', 'b')
tablero.mover('Th6', 'n')
tablero.mover('Txc2', 'b')
tablero.mover('Ta7', 'n')
tablero.mover('Tb2', 'b')
tablero.mover('Ta6', 'n')
tablero.mover('Af7', 'b')
tablero.mover('g4', 'n')
tablero.mover('Ae8', 'b')
tablero.mover('Ta8', 'n')
tablero.mover('Th3', 'b')
tablero.mover('Ae3', 'n')
tablero.mover('Tb4', 'b')
tablero.mover('c4', 'n')
tablero.mover('Txe3', 'b')
tablero.mover('Th8', 'n')
tablero.mover('Ad5', 'b')
tablero.mover('c3', 'n')
tablero.mover('Tc4', 'b')
tablero.mover('f5', 'n')
tablero.mover('Af1', 'b')
tablero.mover('Th6', 'n')
tablero.mover('Tg3', 'b')
tablero.mover('Ad6', 'n')
tablero.mover('Tg2', 'b')
tablero.mover('Af3', 'n')
tablero.mover('Tc8', 'b')
tablero.mover('Ae4', 'n')
tablero.mover('Axg4', 'b')
tablero.mover('Ta5', 'n')
tablero.mover('Ad1', 'b')
tablero.mover('Af3', 'n')
tablero.mover('Tc5', 'b')
tablero.mover('Ad5', 'n')
tablero.mover('Af7', 'b')
tablero.mover('f4', 'n')
tablero.mover('Ag5', 'b')
tablero.mover('Af3', 'n')
tablero.mover('b6', 'b')
tablero.mover('Th8', 'n')
tablero.mover('Axf4', 'b')
tablero.mover('c2', 'n')
tablero.mover('Axc2', 'b')
tablero.mover('Ta7', 'n')
tablero.mover('Ag7', 'b')
tablero.mover('Ag6', 'n')
tablero.mover('Tb5', 'b')
tablero.mover('Af5', 'n')
tablero.mover('Td5', 'b')
tablero.mover('Ta8', 'n')
tablero.mover('Ae5', 'b')
tablero.mover('Ae6', 'n')
tablero.mover('Ad6', 'b')
tablero.mover('Af7', 'n')
tablero.mover('Tf5', 'b')
tablero.mover('Th6', 'n')
tablero.mover('Tg4', 'b')
tablero.mover('Ae6', 'n')
tablero.mover('Tf3', 'b')
tablero.mover('Th7', 'n')
tablero.mover('Te4', 'b')
tablero.mover('Ta7', 'n')
tablero.mover('Tb4', 'b')
tablero.mover('Tc7', 'n')
tablero.mover('Td4', 'b')
tablero.mover('Th6', 'n')
tablero.mover('Af1', 'b')
tablero.mover('Tg6', 'n')
tablero.mover('Ad1', 'b')
tablero.mover('Tf6', 'n')
tablero.mover('Ag2', 'b')
tablero.mover('Axd7', 'n')
tablero.mover('Af5', 'b')
tablero.mover('Ac8', 'n')
tablero.mover('Tc3', 'b')
tablero.mover('Tb7', 'n')
tablero.mover('Axg8', 'b')
tablero.mover('Tg7', 'n')
tablero.mover('Tb4', 'b')
tablero.mover('Axb6', 'n')
tablero.mover('Ad5', 'b')
tablero.mover('Tf4', 'n')
tablero.mover('Tg3', 'b')
tablero.mover('Tc4', 'n')
tablero.mover('f4', 'b')
tablero.mover('Ac5', 'n')
tablero.mover('Tb6', 'b')
tablero.mover('Tc3', 'n')
tablero.mover('Txb8', 'b')
tablero.mover('Ad6', 'n')
tablero.mover('Txg7', 'b')
tablero.mover('Ae7', 'n')
tablero.mover('Ad7', 'b')
tablero.mover('Ad6', 'n')
tablero.mover('Tg1', 'b')
tablero.mover('Ac7', 'n')
tablero.mover('Tg4', 'b')
tablero.mover('Ab4', 'n')
tablero.mover('Tg6', 'b')
tablero.mover('Ae7', 'n')
tablero.mover('Ac8', 'b')
tablero.mover('Txa3', 'n')
tablero.mover('Ac4', 'b')
tablero.mover('Tg3', 'n')
tablero.mover('Ae6', 'b')
tablero.mover('Ac3', 'n')
tablero.mover('Ad7', 'b')
tablero.mover('Ab6', 'n')
tablero.mover('Ta8', 'b')
tablero.mover('a3', 'n')
tablero.mover('Ta6', 'b')
tablero.mover('Tg2', 'n')
tablero.mover('Tg3', 'b')
tablero.mover('Tg1', 'n')
tablero.mover('Th3', 'b')
tablero.mover('Ae2', 'n')
tablero.mover('Te3', 'b')
tablero.mover('Ad1', 'n')
tablero.mover('Te4', 'b')
tablero.mover('Tg3', 'n')
tablero.mover('Te8', 'b')
tablero.mover('Tc3', 'n')
tablero.mover('Af5', 'b')
tablero.mover('Tf3', 'n')
tablero.mover('Ta8', 'b')
tablero.mover('Axf4', 'n')
tablero.mover('Te6', 'b')
tablero.mover('Ag2', 'n')
tablero.mover('Tb8', 'b')
tablero.mover('Ad6', 'n')
tablero.mover('Ag4', 'b')
tablero.mover('Ac5', 'n')
tablero.mover('Ab5', 'b')
tablero.mover('Te3', 'n')
tablero.mover('Ta8', 'b')
tablero.mover('Ab3', 'n')
tablero.mover('Ae8', 'b')
tablero.mover('Td3', 'n')
tablero.mover('Te3', 'b')
tablero.mover('Td1', 'n')
tablero.mover('Ad7', 'b')
tablero.mover('Td6', 'n')
tablero.mover('Txb3', 'b')
tablero.mover('Tb6', 'n')
tablero.mover('Ae2', 'b')
tablero.mover('Tf6', 'n')
tablero.mover('Ac6', 'b')
tablero.mover('Tf8', 'n')
tablero.mover('Ta7', 'b')
tablero.mover('Tf3', 'n')
tablero.mover('Te7', 'b')
tablero.mover('Td3', 'n')
tablero.mover('Axd3', 'b')

# SD --> 
# SI -->
# BI -->
# BD --> 
# SD con pieza en medio. --> 
# SI con pieza en destino. --> 
# SD con pieza en medio. --> 
# SD con pieza en destino. --> 
# BD con pieza en medio. --> 
# BD con pieza en destino. --> 
# BI con pieza en medio. --> 
# BI con pieza en destino. --> 

# Movimientos al azar.
#tablero.movimientosAlAzar(1000)
print("\n" + str(tablero))
